

//ENTER A NUMBER
//INCLUDE A FORM - INCREMENT IS OUTPUTTED AS A SUM OF PREVIOUS NUMBER
//ALSO SHOW THE MEAN
//RESET BUTTON STARTS EVERYTHING OVER AT ZERO
//ALSO PREVENTION OF ANYTHING OTHER THAN A NUMBER BEING ERRORED - OR MAKE IT COME ACROSS AS AN ERROR - AND IT DISPLAYS A MESSAGE THAT SAYS "ERROR"

//JQUERY HAS A .value
//YOU'LL HAVE AN ONCLICK FOR THE SUBMIT
f